dist: xenial

addons:
    snaps:
        - hugo

before_install:
    - mkdir src/
    - mv archetypes config.yaml content layouts static themes src/

script:
    - cd src
    - hugo -t cocoa-eh
    - cd ..

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    committer-from-gh: true
    verbose: true
    on:
        branch: master
