dist: xenial

addons:
    snaps:
        - hugo

script:
    - hugo

deploy:
    local-dir: public/
    provider: pages
    repo: coditva/coditva.github.io
    target-branch: master
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    committer-from-gh: true
    verbose: true
    on:
        branch: master

cache:
    directories:
        - public/
