layoutDir = "layouts"
publishDir = "."
buildDrafts = false
baseURL = "https://utkarshme.github.io"
languageCode = "en-us"
title = "Utkarsh Maheshwari"
author = "Utkarsh Maheshwari"

theme = "cocoa"
sectionPagesMenu = "main"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    avatar = "img/profile.jpg"
    latestpostscount       = 5                             # how many posts to display on the home page
    i18n_flags             = false                         # whether to display small country flags for available translations
    author                 = "Utkarsh Maheshwari"
    cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
    dateform               = "Jan 2, 2006"
    dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
    description            = "Coding is an art and I'm a purist"
    email                  = "utkarshme96@gmail.com"
    faviconfile            = "img/favicon.ico"
    highlightjs            = true
    lang                   = "en"
    noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
    selfintro              = ""                            # appears in the site header when set to a non-empty string
    github                 = "https://github.com/UtkarshMe"
    linkedin               = "https://www.linkedin.com/in/utkarshme96/"
    twitter                = "https://twitter.com/utkarshme96"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"
