baseURL             : "https://coditva.dev/"            # must end with "/"
languageCode        : "en"
title               : "Coditva | coditva.dev"
author              : "coditva"
googleAnalytics     : "UA-109205422-1"
disqusshortname     : "utkarshme"

theme               : "black-and-light"

pygmentsCodefences  : true
pygmentsStyle       : "tango"
pygmentsOptions:
  - "linenos"
  - "noclasses"
  - "full"

buildDrafts         : false
canonifyurls        : true
contentdir          : "content"

taxonomies:
  tag               : "tags"

permalinks:
  blog              : "blog/:slug/"

params:
  sitename          : "coditva.dev"
  disableWebFonts   : false

menu:
  main:
    - name  : "home"
      url   : "/"
      weight: 1

    - name  : "about"
      url   : "/me"
      weight: 2

    - name  : "feed"
      url   : "/index.xml"
      weight: 4
