baseURL             : "https://coditva.dev/"            # must end with "/"
languageCode        : "en"
title               : "Coditva | coditva.dev"
author              : "coditva"
googleAnalytics     : "UA-109205422-1"
disqusshortname     : "utkarshme"

theme               : "black-and-light"

pygmentsCodefences  : true
pygmentsStyle       : "tango"
pygmentsOptions:
  - "linenos"
  - "noclasses"
  - "full"

buildDrafts         : false
canonifyurls        : true
contentdir          : "content"

taxonomies:
  tag               : "tags"

permalinks:
  blog              : "blog/:slug/"

params:
  sitename          : "coditva.dev"
  disableWebFonts   : false

menu:
  main:
    - name  : home
      url   : /
      weight: 1

    - name  : about
      url   : /me
      weight: 2

    - name  : feed
      url   : /index.xml
      weight: 3

  social:
    - name  : Mail
      title : coditva@gmail.com
      url   : mailto:coditva@gmail.com
      weight: 1

    - name  : GitHub
      title : coditva
      url   : https://github.com/coditva
      weight: 2

    - name  : Twitter
      title : coditva
      url   : https://twitter.com/coditva
      weight: 3

    - name  : Resume
      title : pdf
      url   : /resume.pdf
      weight: 4

    - name  : PGP
      title : 5A40E60FB40CDEBE
      url   : https://pgp.mit.edu/pks/lookup?op=get&search=0x5A40E60FB40CDEBE
      weight: 5
