layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
baseURL = "https://utkarshme.github.io"
languageCode = "en-us"
title = "Utkarsh Maheshwari"
theme = "minimo"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  subtitle = "Coding is an art and I am a purist."
  author = "John Doe"
