# vi:set filetype=yaml

publishDir          = ".."
buildDrafts         = false
baseURL             = "https://utkarshme.github.io"
languageCode        = "en-us"
title               = "Utkarsh Maheshwari"
author              = "Utkarsh Maheshwari"
googleAnalytics     = "UA-109205422-1"
                   
theme               = "cocoa"
sectionPagesMenu    = "main"

[taxonomies]
    category            = "categories"
    tag                 = "tags"

[params]
    avatar              = "img/profile.jpg"
    author              = "Utkarsh Maheshwari"
    selfintro           = "Code is beautiful, if you have the eye for it."
    email               = "utkarshme96@gmail.com"
    faviconfile         = "img/favicon.ico"
    lang                = "en"
    dateform            = "Jan 2, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 IST"
    latestpostscount    = 5      # num of posts to display on the home page
    i18n_flags          = false  # display country flags for translations
    cachebuster         = true   # add unix timestamp in query string
    noshowreadtime      = false  # if true, don't show "<x> minutes read"
    highlightjs         = true

    github              = "https://github.com/UtkarshMe"
    linkedin            = "https://www.linkedin.com/in/utkarshme96/"
    twitter             = "https://twitter.com/utkarshme96"


[[menu.main]]
    name        = "Home"
    weight      = 1
    identifier  = "home"
    url         = "/"
[[menu.main]]
    name        = "Blog"
    weight      = 2
    identifier  = "blog"
    url         = "/blog"
[[menu.main]]
    name        = "About"
    weight      = 3
    identifier  = "about"
    url         = "/about"
[[menu.main]]
    name        = "Projects"
    weight      = 4
    identifier  = "projects"
    url         = "/projects"
[[menu.main]]
    name        = "Github"
    weight      = 98
    identifier  = "github"
    url         = "https://github.com/UtkarshMe"
[[menu.main]]
    name        = "Resume"
    weight      = 99
    identifier  = "resume"
    url         = "resume.pdf"
