layoutDir = "layouts"
publishDir = ".."
buildDrafts = false
baseURL = "https://utkarshme.github.io"
languageCode = "en-us"
title = "Utkarsh Maheshwari"
author = "Utkarsh Maheshwari"
googleAnalytics     = "UA-109205422-1"

theme = "cocoa"
sectionPagesMenu = "main"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    avatar = "img/profile.jpg"
    latestpostscount       = 5                             # how many posts to display on the home page
    i18n_flags             = false                         # whether to display small country flags for available translations
    author                 = "Utkarsh Maheshwari"
    cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
    dateform               = "Jan 2, 2006"
    dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
    selfintro              = "Code is beautiful, if you have the eye for it."
    email                  = "utkarshme96@gmail.com"
    faviconfile            = "img/favicon.ico"
    highlightjs            = true
    lang                   = "en"
    noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
    github                 = "https://github.com/UtkarshMe"
    linkedin               = "https://www.linkedin.com/in/utkarshme96/"
    twitter                = "https://twitter.com/utkarshme96"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about"
[[menu.main]]
    name = "Projects"
    weight = 4
    identifier = "projects"
    url = "/projects"
[[menu.main]]
    name = "Github"
    weight = 99
    identifier = "github"
    url = "https://github.com/UtkarshMe"
[[menu.main]]
    name = "Resume"
    weight = 99
    identifier = "resume"
    url = "resume.pdf"
